create table if not exists public.daily_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  entry_date date not null,
  content text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint daily_notes_user_entry_date_key unique (user_id, entry_date),
  constraint daily_notes_content_size_check
    check (octet_length(content) <= 1048576)
);

create index if not exists daily_notes_user_updated_at_idx
  on public.daily_notes (user_id, updated_at desc);

alter table public.daily_notes enable row level security;

revoke all privileges on table public.daily_notes from anon, authenticated;
grant select, insert, update on table public.daily_notes to authenticated;

revoke all privileges on sequence public.daily_notes_id_seq from anon, authenticated;
grant usage on sequence public.daily_notes_id_seq to authenticated;

drop policy if exists "users can read their own daily notes" on public.daily_notes;
create policy "users can read their own daily notes"
  on public.daily_notes
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "users can create their own daily notes" on public.daily_notes;
create policy "users can create their own daily notes"
  on public.daily_notes
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "users can update their own daily notes" on public.daily_notes;
create policy "users can update their own daily notes"
  on public.daily_notes
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create table if not exists public.daily_note_versions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  entry_date date not null,
  content text not null,
  created_at timestamptz not null default now(),
  constraint daily_note_versions_content_size_check
    check (octet_length(content) <= 1048576)
);

create index if not exists daily_note_versions_user_entry_created_idx
  on public.daily_note_versions (user_id, entry_date, created_at desc);

create index if not exists daily_note_versions_user_created_at_idx
  on public.daily_note_versions (user_id, created_at desc);

alter table public.daily_note_versions enable row level security;

revoke all privileges on table public.daily_note_versions from anon, authenticated;
grant select, insert on table public.daily_note_versions to authenticated;

revoke all privileges on sequence public.daily_note_versions_id_seq from anon, authenticated;
grant usage on sequence public.daily_note_versions_id_seq to authenticated;

drop policy if exists "users can read their own daily note versions"
  on public.daily_note_versions;
create policy "users can read their own daily note versions"
  on public.daily_note_versions
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "users can create their own daily note versions"
  on public.daily_note_versions;
create policy "users can create their own daily note versions"
  on public.daily_note_versions
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

insert into public.daily_notes (
  user_id,
  entry_date,
  content,
  created_at,
  updated_at
)
select
  notes.user_id,
  coalesce(notes.last_entry_date, notes.updated_at::date, current_date),
  notes.content,
  notes.updated_at,
  notes.updated_at
from public.notes
on conflict (user_id, entry_date) do nothing;

insert into public.daily_note_versions (user_id, entry_date, content, created_at)
select
  daily_notes.user_id,
  daily_notes.entry_date,
  daily_notes.content,
  daily_notes.updated_at
from public.daily_notes
where daily_notes.content <> ''
  and not exists (
    select 1
    from public.daily_note_versions
    where daily_note_versions.user_id = daily_notes.user_id
      and daily_note_versions.entry_date = daily_notes.entry_date
  );

create or replace function public.archive_daily_note_before_update()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if old.content is distinct from new.content
    and not exists (
      select 1
      from public.daily_note_versions
      where user_id = old.user_id
        and entry_date = old.entry_date
        and created_at >= statement_timestamp() - interval '10 minutes'
    )
  then
    insert into public.daily_note_versions (user_id, entry_date, content)
    values (old.user_id, old.entry_date, old.content);
  end if;

  new.updated_at = statement_timestamp();
  return new;
end;
$$;

revoke all on function public.archive_daily_note_before_update() from public, anon;
grant execute on function public.archive_daily_note_before_update() to authenticated;

drop trigger if exists daily_notes_archive_before_update on public.daily_notes;
create trigger daily_notes_archive_before_update
  before update of content on public.daily_notes
  for each row
  when (old.content is distinct from new.content)
  execute function public.archive_daily_note_before_update();

create or replace function public.mirror_legacy_note_to_daily()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  insert into public.daily_notes (user_id, entry_date, content, created_at, updated_at)
  values (
    new.user_id,
    coalesce(new.last_entry_date, new.updated_at::date, current_date),
    new.content,
    new.updated_at,
    new.updated_at
  )
  on conflict (user_id, entry_date) do update
  set content = excluded.content,
      updated_at = excluded.updated_at;

  return new;
end;
$$;

revoke all on function public.mirror_legacy_note_to_daily() from public, anon;
grant execute on function public.mirror_legacy_note_to_daily() to authenticated;

drop trigger if exists notes_mirror_to_daily on public.notes;
create trigger notes_mirror_to_daily
  after insert or update of content, last_entry_date on public.notes
  for each row
  execute function public.mirror_legacy_note_to_daily();
