create table if not exists public.moments (
  id bigint generated by default as identity primary key,
  content text not null,
  source text default 'generated',
  mood text default 'quiet',
  created_at timestamptz default now()
);

create index if not exists moments_created_at_desc_idx
  on public.moments (created_at desc);

alter table public.moments enable row level security;

revoke all privileges on table public.moments from anon, authenticated;
grant select, insert on table public.moments to anon, authenticated;
grant usage on sequence public.moments_id_seq to anon, authenticated;

drop policy if exists "allow read moments" on public.moments;
create policy "allow read moments"
  on public.moments
  for select
  to anon
  using (true);

drop policy if exists "allow insert moments" on public.moments;
create policy "allow insert moments"
  on public.moments
  for insert
  to anon, authenticated
  with check (char_length(btrim(content)) between 1 and 120);
