alter table public.notes
  add column if not exists last_entry_date date;

create table if not exists public.moment_traces (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  content text not null,
  weather_text text,
  temperature text,
  location text,
  daypart text not null,
  created_at timestamptz not null default now(),
  constraint moment_traces_content_check
    check (char_length(btrim(content)) between 1 and 120),
  constraint moment_traces_weather_text_check
    check (weather_text is null or char_length(weather_text) <= 48),
  constraint moment_traces_temperature_check
    check (temperature is null or char_length(temperature) <= 12),
  constraint moment_traces_location_check
    check (location is null or char_length(location) <= 96),
  constraint moment_traces_daypart_check
    check (daypart in ('morning', 'day', 'evening', 'night'))
);

create index if not exists moment_traces_user_created_at_idx
  on public.moment_traces (user_id, created_at desc);

alter table public.moment_traces enable row level security;

revoke all privileges on table public.moment_traces from anon, authenticated;
grant select, insert on table public.moment_traces to authenticated;
grant usage on sequence public.moment_traces_id_seq to authenticated;

drop policy if exists "users can read their own traces" on public.moment_traces;
create policy "users can read their own traces"
  on public.moment_traces
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "users can create their own traces" on public.moment_traces;
create policy "users can create their own traces"
  on public.moment_traces
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "allow insert moments" on public.moments;
revoke insert on table public.moments from anon, authenticated;

grant select on table public.moments to authenticated;
drop policy if exists "allow authenticated read moments" on public.moments;
create policy "allow authenticated read moments"
  on public.moments
  for select
  to authenticated
  using (true);
