create table public.note_versions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  content text not null,
  last_entry_date date,
  created_at timestamptz not null default now(),
  constraint note_versions_content_size_check
    check (octet_length(content) <= 1048576)
);

create index note_versions_user_created_at_idx
  on public.note_versions (user_id, created_at desc);

alter table public.note_versions enable row level security;
